# -*- coding: utf-8 -*-
"""Submitted Pulse.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XYPRH5ZIJn8cY_0XwmydckWFP06j9XNw
"""

# STEP 1: Install necessary libraries in Google Colab
!pip install -q -U google-generativeai streamlit beautifulsoup4 requests pyngrok

# STEP 2: Import libraries
import streamlit as st
import google.generativeai as genai
import requests
from bs4 import BeautifulSoup, Comment
from urllib.parse import urljoin, urlparse
import json
import time
import os # <--- Import os for environment variables
import re
from pyngrok import ngrok
import logging
import sys

# STEP 3: Configure Logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# STEP 4: HARDCODE API Key and Ngrok Token (INSECURE - USE WITH CAUTION)

# --- WARNING: HARDCODING KEYS IS INSECURE ---
# Replace "YOUR_GEMINI_API_KEY_HERE" with your actual key.
# Replace "YOUR_NGROK_AUTH_TOKEN_HERE" with your actual token.
# Do NOT share this code with keys embedded. Use secrets management for real applications.
HARDCODED_GOOGLE_API_KEY = " " # <--- REPLACE THIS
HARDCODED_NGROK_AUTH_TOKEN = " " # <--- REPLACE THIS

if "YOUR_GEMINI_API_KEY_HERE" in HARDCODED_GOOGLE_API_KEY or not HARDCODED_GOOGLE_API_KEY:
    logging.error("CRITICAL: Placeholder for GOOGLE_API_KEY is not replaced. Exiting.")
    st.error("CRITICAL: Placeholder for GOOGLE_API_KEY is not replaced in the code. Please edit the script.")
    sys.exit("Exiting due to missing Gemini API Key.") # Stop execution

if "YOUR_NGROK_AUTH_TOKEN_HERE" in HARDCODED_NGROK_AUTH_TOKEN or not HARDCODED_NGROK_AUTH_TOKEN:
    logging.error("CRITICAL: Placeholder for NGROK_AUTH_TOKEN is not replaced. Ngrok will likely fail.")

# STEP 5: Configure Gemini API and Ngrok using hardcoded values

try:
    genai.configure(api_key=HARDCODED_GOOGLE_API_KEY)
    model = genai.GenerativeModel('gemini-1.5-flash')
    logging.info("Gemini API Key configured successfully using hardcoded value.")
except Exception as e:
    st.error(f"Error configuring Gemini API Key: {e}. Check the hardcoded key.")
    logging.error(f"Error configuring Gemini API Key: {e}. Check the hardcoded key.")
    model = None

try:
    ngrok.set_auth_token(HARDCODED_NGROK_AUTH_TOKEN)
    logging.info("Ngrok Authtoken configured successfully using hardcoded value.")
except Exception as e:
    st.error(f"Error configuring Ngrok Authtoken: {e}. Check the hardcoded token.")
    logging.error(f"Error configuring Ngrok Authtoken: {e}. Check the hardcoded token.")

# STEP 6: Core Functions (Crawling, Extraction, AI Interaction)

MAX_PAGES_TO_CRAWL = 15
REQUEST_TIMEOUT = 10
DELAY_BETWEEN_REQUESTS = 0.5

session = requests.Session()
session.headers.update({'User-Agent': 'PulseModuleExtractorAI/1.0'})

def is_valid_url(url):
    try:
        result = urlparse(url)
        return all([result.scheme in ['http', 'https'], result.netloc])
    except ValueError:
        return False

def clean_text(text):
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()
    return text

def extract_meaningful_content(soup, url):
    for element in soup(["script", "style", "header", "footer", "nav", "aside", "form", "button", "iframe", "noscript"]):
        element.decompose()
    for comment in soup.find_all(string=lambda text: isinstance(text, Comment)):
        comment.extract()

    potential_containers = [
        soup.find('main'), soup.find('article'), soup.find(id='content'),
        soup.find(id='main-content'), soup.find(class_='content'),
        soup.find(class_='main-content'), soup.find(class_='post-content'),
        soup.find(class_='entry-content'), soup.find(role='main'),
        soup.find(class_='article-body'), soup.find(class_='hc-article-body'),
    ]
    content_element = None
    for container in potential_containers:
        if container:
            content_element = container
            logging.debug(f"Found potential main content container: {content_element.name} {content_element.attrs.get('id', '')} {content_element.attrs.get('class', '')} on {url}")
            break
    if not content_element:
        content_element = soup.body
        logging.warning(f"No specific main content container found on {url}, falling back to body.")
        if not content_element:
             logging.error(f"Could not find body tag on {url}. Skipping content extraction.")
             return ""

    text_parts = []
    if content_element:
      for element in content_element.find_all(['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'li', 'td', 'th', 'div']):
          element_text = element.get_text(separator=' ', strip=True)
          if element_text and len(element_text) > 10:
              tag_name = element.name.lower()
              prefix = ""
              if tag_name.startswith('h'): prefix = f"\n## {tag_name.upper()}: "
              elif tag_name == 'li': prefix = "\n* "
              elif tag_name in ['td', 'th']: prefix = " | "
              cleaned_part = clean_text(element_text)
              if cleaned_part: text_parts.append(prefix + cleaned_part)

      if not text_parts or len(" ".join(text_parts)) < 100:
          logging.warning(f"Specific tag extraction yielded little text on {url}, using broader get_text().")
          full_text = content_element.get_text(separator='\n', strip=True)
          lines = [clean_text(line) for line in full_text.splitlines() if clean_text(line)]
          text_parts = lines

    return "\n".join(text_parts)

def crawl_website(start_url, max_pages=MAX_PAGES_TO_CRAWL):
    if not is_valid_url(start_url):
        logging.error(f"Invalid start URL: {start_url}")
        return {}, set()
    parsed_start_url = urlparse(start_url)
    base_domain = parsed_start_url.netloc
    start_path = parsed_start_url.path if parsed_start_url.path else "/"
    allowed_prefixes = ["/"]
    if 'support.' in base_domain or 'help.' in base_domain or '/hc/' in start_path:
        allowed_prefixes = ['/hc/', '/support/', '/help/', '/docs/']
        common_hc_segments = ['/hc/en-us', '/support/en-us', '/help/en-us', '/docs/']
        for seg in common_hc_segments:
             if seg in start_path:
                  prefix = start_path.split(seg)[0] + seg
                  if prefix not in allowed_prefixes: allowed_prefixes.append(prefix)
                  break
    logging.info(f"Starting crawl: {start_url} Domain: {base_domain} Prefixes: {allowed_prefixes}")
    urls_to_visit = {start_url}
    visited_urls = set()
    content_map = {}
    pages_crawled = 0
    while urls_to_visit and pages_crawled < max_pages:
        current_url = urls_to_visit.pop()
        if current_url in visited_urls: continue
        time.sleep(DELAY_BETWEEN_REQUESTS)
        logging.info(f"Crawling ({pages_crawled + 1}/{max_pages}): {current_url}")
        try:
            response = session.get(current_url, timeout=REQUEST_TIMEOUT, allow_redirects=True)
            response.raise_for_status()
            final_url = response.url
            if final_url in visited_urls: continue
            visited_urls.add(current_url); visited_urls.add(final_url)
            pages_crawled += 1
            content_type = response.headers.get('content-type', '').lower()
            if 'html' not in content_type:
                logging.warning(f"Skipping non-HTML content ({content_type}) at: {final_url}")
                continue
            soup = BeautifulSoup(response.text, 'html.parser')
            page_title = clean_text(soup.title.string if soup.title else "No Title Found")
            extracted_text = extract_meaningful_content(soup, final_url)
            if extracted_text:
                 content_map[final_url] = f"--- Page: {final_url} ---\nTitle: {page_title}\n\n{extracted_text}\n\n---\n"
                 logging.info(f"Extracted ~{len(extracted_text)} chars from {final_url}")
            else:
                 logging.warning(f"No meaningful content extracted from {final_url}")
                 content_map[final_url] = f"--- Page: {final_url} ---\nTitle: {page_title}\n\n[No meaningful content extracted]\n\n---\n"

            if pages_crawled < max_pages:
                 for link in soup.find_all('a', href=True):
                    href = link['href']
                    absolute_url = urljoin(final_url, href)
                    parsed_absolute_url = urlparse(absolute_url)
                    absolute_url = parsed_absolute_url._replace(fragment="").geturl() # Remove fragment
                    if (is_valid_url(absolute_url) and
                        parsed_absolute_url.netloc == base_domain and
                        absolute_url not in visited_urls and
                        absolute_url not in urls_to_visit and
                        any(parsed_absolute_url.path.startswith(prefix) for prefix in allowed_prefixes)):
                         path_lower = parsed_absolute_url.path.lower()
                         query_lower = parsed_absolute_url.query.lower()
                         if not any(ext in path_lower for ext in ['.pdf', '.zip', '.jpg', '.png', '.gif', '.css', '.js']) and \
                           not any(kw in path_lower for kw in ['/login', '/signup', '/pricing', '/contact', '/blog', '/about']) and \
                           not any(kw in query_lower for kw in ['mailto:', 'tel:']):
                            urls_to_visit.add(absolute_url)
        except requests.exceptions.RequestException as e:
            logging.error(f"Request failed for {current_url}: {e}")
            visited_urls.add(current_url)
        except Exception as e:
            logging.error(f"Error processing {current_url}: {e}")
            visited_urls.add(current_url)
    logging.info(f"Crawling finished. Visited {len(visited_urls)} URLs. Extracted content from {len(content_map)} URLs.")
    return content_map, visited_urls


def generate_modules_with_gemini(all_text_content):
    """Uses Gemini to identify modules/submodules and generate descriptions."""
    if 'model' not in globals() or model is None:
         logging.error("Gemini model is not initialized. Cannot generate modules.")
         return None, "Error: Gemini model was not initialized correctly. Check API Key configuration."

    if not all_text_content:
         logging.error("No text content provided to Gemini.")
         return None, "Error: No text content was extracted from the URL(s)."

    full_context = "\n".join(all_text_content.values())
    max_context_length = 900000
    if len(full_context) > max_context_length:
        logging.warning(f"Context length ({len(full_context)} chars) exceeds limit, truncating.")
        full_context = full_context[:max_context_length]

    prompt = f"""
    Analyze the following documentation content extracted from a help website. Your goal is to identify the key functional modules and their corresponding submodules described in the text.

    Based *only* on the text provided below, perform the following tasks:
    1.  Identify the main top-level modules (major feature areas or categories).
    2.  For each module, provide a concise and accurate description summarizing its purpose, using *only* information present in the text.
    3.  Under each module, identify its relevant submodules (specific tasks or sub-topics).
    4.  For each submodule, provide a concise and accurate description explaining its function, using *only* information present in the text.
    5.  Structure the output *strictly* as a JSON list of objects. Each object represents a module and must have keys: "module" (String), "Description" (String), "Submodules" (Object where keys are submodule names (String) and values are their descriptions (String)). If a module has no clear submodules based on the text, provide an empty object {{}}.

    Example Format:
    [
      {{
        "module": "Module_1",
        "Description": "Detailed description of the module based on text.",
        "Submodules": {{
          "submodule_1a": "Detailed description of submodule 1a based on text."
        }}
      }},
      {{
        "module": "Module_2",
        "Description": "Detailed description of the module based on text.",
        "Submodules": {{}}
      }}
    ]

    IMPORTANT RULES:
    - Base ALL names and descriptions *strictly* on the content provided. Do not invent features or use external knowledge.
    - If text lacks info, make a best effort or omit.
    - Ensure the output is valid JSON. Do not include any text before or after the JSON list (like ```json or ```).

    Documentation Content:
    --- START CONTENT ---
    {full_context}
    --- END CONTENT ---

    JSON Output:
    """
    logging.info(f"Sending prompt to Gemini (Context size: {len(full_context)} chars)...")
    try:
        response = model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(temperature=0.2)
        )
        raw_response_text = response.text.strip()
        if raw_response_text.startswith("```json"): raw_response_text = raw_response_text[7:]
        if raw_response_text.endswith("```"): raw_response_text = raw_response_text[:-3]
        raw_response_text = raw_response_text.strip()
        logging.info("Received response from Gemini.")
        try:
            result_json = json.loads(raw_response_text)
            if not isinstance(result_json, list): raise ValueError("Expected JSON list.")
            for item in result_json:
                if not isinstance(item, dict): raise ValueError("List items must be objects.")
                if not all(k in item for k in ["module", "Description", "Submodules"]): raise ValueError("Module object missing required keys.")
                if not isinstance(item["Submodules"], dict): raise ValueError("'Submodules' key must contain an object.")
            logging.info("Successfully parsed and validated JSON response from Gemini.")
            return result_json, None
        except (json.JSONDecodeError, ValueError) as e:
            logging.error(f"Invalid JSON from Gemini: {e}. Response: {raw_response_text[:500]}...")
            return None, f"Error: AI generated invalid/unexpected JSON format. {e}\nPreview:\n{raw_response_text[:500]}..."
    except Exception as e:
        logging.error(f"Error calling Gemini API: {e}")
        return None, f"Error: Failed to get response from AI. {e}"


# STEP 7: Streamlit Application Code (Written to File)


app_code = """
import streamlit as st
import google.generativeai as genai
import requests
from bs4 import BeautifulSoup, Comment
from urllib.parse import urljoin, urlparse
import json
import time
import os # <--- Needs os for environment variables
import re
import logging
import sys

# --- Configure Logging (within Streamlit app process) ---
logging.basicConfig(level=logging.INFO, format='%(asctime)s - StreamlitApp - %(levelname)s - %(message)s')

# --- Re-include necessary functions here ---
# (Copy Step 6 functions: is_valid_url, clean_text, extract_meaningful_content, crawl_website, generate_modules_with_gemini)
# IMPORTANT: Copy all functions from Step 6 above into this block.
# Make sure session, MAX_PAGES_TO_CRAWL etc are defined as well.

# --- Start Copied Functions ---

MAX_PAGES_TO_CRAWL = 15
REQUEST_TIMEOUT = 10
DELAY_BETWEEN_REQUESTS = 0.5
session = requests.Session()
session.headers.update({'User-Agent': 'PulseModuleExtractorAI/1.0'})

def is_valid_url(url):
    try:
        result = urlparse(url)
        return all([result.scheme in ['http', 'https'], result.netloc])
    except ValueError:
        return False

def clean_text(text):
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()
    return text

def extract_meaningful_content(soup, url):
    for element in soup(["script", "style", "header", "footer", "nav", "aside", "form", "button", "iframe", "noscript"]):
        element.decompose()
    for comment in soup.find_all(string=lambda text: isinstance(text, Comment)):
        comment.extract()
    potential_containers = [
        soup.find('main'), soup.find('article'), soup.find(id='content'),
        soup.find(id='main-content'), soup.find(class_='content'),
        soup.find(class_='main-content'), soup.find(class_='post-content'),
        soup.find(class_='entry-content'), soup.find(role='main'),
        soup.find(class_='article-body'), soup.find(class_='hc-article-body'),
    ]
    content_element = None
    for container in potential_containers:
        if container:
            content_element = container
            logging.debug(f"Found potential main content container on {url}")
            break
    if not content_element:
        content_element = soup.body
        logging.warning(f"Falling back to body on {url}")
        if not content_element: return ""
    text_parts = []
    if content_element:
      for element in content_element.find_all(['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'li', 'td', 'th', 'div']):
          element_text = element.get_text(separator=' ', strip=True)
          if element_text and len(element_text) > 10:
              tag_name = element.name.lower()
              prefix = ""
              if tag_name.startswith('h'): prefix = f"\\n## {tag_name.upper()}: "
              elif tag_name == 'li': prefix = "\\n* "
              elif tag_name in ['td', 'th']: prefix = " | "
              cleaned_part = clean_text(element_text)
              if cleaned_part: text_parts.append(prefix + cleaned_part)
      if not text_parts or len(" ".join(text_parts)) < 100:
          logging.warning(f"Specific tag extraction yielded little text on {url}, using broader get_text().")
          full_text = content_element.get_text(separator='\\n', strip=True)
          lines = [clean_text(line) for line in full_text.splitlines() if clean_text(line)]
          text_parts = lines
    return "\\n".join(text_parts)


def crawl_website(start_url, max_pages=MAX_PAGES_TO_CRAWL):
    if not is_valid_url(start_url):
        logging.error(f"Invalid start URL: {start_url}")
        return {}, set()
    parsed_start_url = urlparse(start_url)
    base_domain = parsed_start_url.netloc
    start_path = parsed_start_url.path if parsed_start_url.path else "/"
    allowed_prefixes = ["/"]
    if 'support.' in base_domain or 'help.' in base_domain or '/hc/' in start_path:
        allowed_prefixes = ['/hc/', '/support/', '/help/', '/docs/']
        common_hc_segments = ['/hc/en-us', '/support/en-us', '/help/en-us', '/docs/']
        for seg in common_hc_segments:
             if seg in start_path:
                  prefix = start_path.split(seg)[0] + seg
                  if prefix not in allowed_prefixes: allowed_prefixes.append(prefix)
                  break
    logging.info(f"Starting crawl: {start_url} Domain: {base_domain} Prefixes: {allowed_prefixes}")
    urls_to_visit = {start_url}
    visited_urls = set()
    content_map = {}
    pages_crawled = 0
    while urls_to_visit and pages_crawled < max_pages:
        current_url = urls_to_visit.pop()
        if current_url in visited_urls: continue
        time.sleep(DELAY_BETWEEN_REQUESTS)
        logging.info(f"Crawling ({pages_crawled + 1}/{max_pages}): {current_url}")
        try:
            response = session.get(current_url, timeout=REQUEST_TIMEOUT, allow_redirects=True)
            response.raise_for_status()
            final_url = response.url
            if final_url in visited_urls: continue
            visited_urls.add(current_url); visited_urls.add(final_url)
            pages_crawled += 1
            content_type = response.headers.get('content-type', '').lower()
            if 'html' not in content_type:
                logging.warning(f"Skipping non-HTML content ({content_type}) at: {final_url}")
                continue
            soup = BeautifulSoup(response.text, 'html.parser')
            page_title = clean_text(soup.title.string if soup.title else "No Title")
            extracted_text = extract_meaningful_content(soup, final_url)
            if extracted_text:
                 content_map[final_url] = f"--- Page: {final_url} ---\\nTitle: {page_title}\\n\\n{extracted_text}\\n\\n---\\n"
                 logging.info(f"Extracted ~{len(extracted_text)} chars from {final_url}")
            else:
                 logging.warning(f"No meaningful content extracted from {final_url}")
                 content_map[final_url] = f"--- Page: {final_url} ---\\nTitle: {page_title}\\n\\n[No meaningful content extracted]\\n\\n---\\n"

            if pages_crawled < max_pages:
                 for link in soup.find_all('a', href=True):
                    href = link['href']
                    absolute_url = urljoin(final_url, href)
                    parsed_absolute_url = urlparse(absolute_url)
                    absolute_url = parsed_absolute_url._replace(fragment="").geturl()
                    if (is_valid_url(absolute_url) and
                        parsed_absolute_url.netloc == base_domain and
                        absolute_url not in visited_urls and
                        absolute_url not in urls_to_visit and
                        any(parsed_absolute_url.path.startswith(prefix) for prefix in allowed_prefixes)):
                         path_lower = parsed_absolute_url.path.lower()
                         query_lower = parsed_absolute_url.query.lower()
                         if not any(ext in path_lower for ext in ['.pdf', '.zip', '.jpg', '.png', '.gif', '.css', '.js']) and \
                           not any(kw in path_lower for kw in ['/login', '/signup', '/pricing', '/contact', '/blog', '/about']) and \
                           not any(kw in query_lower for kw in ['mailto:', 'tel:']):
                            urls_to_visit.add(absolute_url)
        except requests.exceptions.RequestException as e:
            logging.error(f"Request failed for {current_url}: {e}")
            visited_urls.add(current_url)
        except Exception as e:
            logging.error(f"Error processing {current_url}: {e}")
            visited_urls.add(current_url)
    logging.info(f"Crawling finished. Visited {len(visited_urls)}. Extracted {len(content_map)}.")
    return content_map, visited_urls


# --- Gemini Configuration (within Streamlit app process) ---
# Reads the key passed as environment variable by the main Colab script
model = None
try:
    # V V V IMPORTANT: Read from environment variable V V V
    STREAMLIT_GOOGLE_API_KEY = os.environ.get('GOOGLE_API_KEY')
    # ^ ^ ^ IMPORTANT: Read from environment variable ^ ^ ^
    if STREAMLIT_GOOGLE_API_KEY:
       genai.configure(api_key=STREAMLIT_GOOGLE_API_KEY)
       model = genai.GenerativeModel('gemini-1.5-flash') # Or 'gemini-1.5-pro'
       logging.info("Gemini API Key configured successfully from environment variable.")
    else:
       logging.error("GOOGLE_API_KEY environment variable not found in Streamlit process.")
       # Model remains None
except Exception as e:
    logging.error(f"Error configuring Gemini in Streamlit process: {e}")
    # Model remains None


def generate_modules_with_gemini(all_text_content):
    # Check if the 'model' variable in *this* scope was initialized
    if model is None:
         logging.error("Gemini model is not initialized in Streamlit process. Cannot generate modules.")
         return None, "Error: Gemini model was not initialized correctly in the Streamlit app. Check API Key was passed correctly."

    if not all_text_content: return None, "Error: No text content extracted."

    full_context = "\\n".join(all_text_content.values())
    max_context_length = 900000
    if len(full_context) > max_context_length:
        logging.warning(f"Context length ({len(full_context)} chars) exceeds limit, truncating.")
        full_context = full_context[:max_context_length]

    prompt = f\"\"\"
    Analyze the following documentation content extracted from a help website. Your goal is to identify the key functional modules and their corresponding submodules described in the text.
    Based *only* on the text provided below, perform the following tasks:
    1. Identify the main top-level modules.
    2. For each module, provide a concise description summarizing its purpose using *only* information in the text.
    3. Under each module, identify its relevant submodules.
    4. For each submodule, provide a concise description explaining its function, using *only* information in the text.
    5. Structure the output *strictly* as a JSON list of objects. Each object represents a module with keys: "module" (String), "Description" (String), "Submodules" (Object with submodule names as keys and descriptions as values). If no submodules, use {{}}.
    Example Format: [ {{ "module": "M1", "Description": "D1", "Submodules": {{"s1a": "Ds1a"}} }}, {{ "module": "M2", "Description": "D2", "Submodules": {{}} }} ]
    RULES: Base ALL names and descriptions *strictly* on provided text. Ensure valid JSON output ONLY, no extra text.
    Content:
    --- START CONTENT ---
    {full_context}
    --- END CONTENT ---
    JSON Output:
    \"\"\"
    logging.info(f"Sending prompt to Gemini (Context size: {len(full_context)} chars)...")
    try:
        response = model.generate_content(prompt, generation_config=genai.types.GenerationConfig(temperature=0.2))
        raw_response_text = response.text.strip()
        if raw_response_text.startswith("```json"): raw_response_text = raw_response_text[7:]
        if raw_response_text.endswith("```"): raw_response_text = raw_response_text[:-3]
        raw_response_text = raw_response_text.strip()
        logging.info("Received response from Gemini.")
        try:
            result_json = json.loads(raw_response_text)
            if not isinstance(result_json, list): raise ValueError("Expected JSON list.")
            for item in result_json:
                if not isinstance(item, dict): raise ValueError("List items must be objects.")
                if not all(k in item for k in ["module", "Description", "Submodules"]): raise ValueError("Missing keys.")
                if not isinstance(item["Submodules"], dict): raise ValueError("Submodules must be object.")
            logging.info("Parsed and validated JSON response.")
            return result_json, None
        except (json.JSONDecodeError, ValueError) as e:
            logging.error(f"Invalid JSON from Gemini: {e}. Response: {raw_response_text[:500]}...")
            return None, f"Error: AI generated invalid/unexpected JSON. {e}\\nPreview:\\n{raw_response_text[:500]}..."
    except Exception as e:
        logging.error(f"Gemini API call error: {e}")
        return None, f"Error: Failed AI call. {e}"

# --- End Copied Functions ---


# --- Streamlit App Definition (run_streamlit_app function) ---
def run_streamlit_app():
    st.set_page_config(layout="wide", page_title="Pulse Module Extractor")
    st.title("🚀 Pulse - AI Module Extractor for Help Docs")
    st.markdown("Enter help documentation URL(s) (one per line) to extract modules/submodules using AI.")
    st.warning("🚨 **Security Note:** This version uses hardcoded API keys. Do not use in production or shared environments.", icon="⚠️")

    # Check prerequisites again within the app context (model initialization)
    if model is None:
        st.error("🔴 **CRITICAL:** Gemini model could not be initialized in the Streamlit app. This likely means the `GOOGLE_API_KEY` environment variable was not passed correctly during startup. Please check the main Colab script logs and ensure the key is valid.")
        st.stop() # Stop execution if model isn't ready

    default_urls = [
        "https://support.neo.space/hc/en-us",
        "https://wordpress.org/documentation/",
        "https://help.zluri.com/",
        "https://www.chargebee.com/docs/2.0/"
    ]
    url_input = st.text_area("Enter URLs (one per line):", "\\n".join(default_urls[:1]), height=100)

    # Use the globally defined MAX_PAGES_TO_CRAWL from this script's scope
    max_pages_limit = st.slider("Maximum pages to crawl per starting URL:", min_value=1, max_value=50, value=MAX_PAGES_TO_CRAWL, help="Limits crawling depth.")

    if st.button("✨ Extract Modules", type="primary"):
        urls = [url.strip() for url in url_input.splitlines() if url.strip()]
        if not urls:
            st.warning("Please enter at least one valid URL."); st.stop()
        valid_urls = [url for url in urls if is_valid_url(url)]
        invalid_urls = [url for url in urls if not is_valid_url(url)]
        if invalid_urls: st.warning(f"Ignoring invalid URL(s): {', '.join(invalid_urls)}")
        if not valid_urls: st.error("No valid URLs provided."); st.stop()

        st.info(f"Processing {len(valid_urls)} URL(s)... Max pages per URL: {max_pages_limit}")
        all_extracted_content = {}
        all_visited_urls = set()
        crawling_errors = []
        progress_bar = st.progress(0)
        status_text = st.empty()

        status_text.text("Crawling website(s)...")
        for i, url in enumerate(valid_urls):
            status_text.text(f"Crawling ({i+1}/{len(valid_urls)}): {url}...")
            try:
                # Pass the slider value to the crawl function
                content_map, visited = crawl_website(url, max_pages=max_pages_limit)
                all_extracted_content.update(content_map)
                all_visited_urls.update(visited)
                status_text.text(f"Crawled {url}. Found {len(content_map)} pages with content.")
            except Exception as e:
                st.error(f"Error crawling {url}: {e}")
                logging.error(f"Crawling failed for {url}: {e}")
                crawling_errors.append(f"{url}: {e}")
            progress_bar.progress((i + 1) / (len(valid_urls)*2)) # 50% progress after crawling

        if not all_extracted_content:
            st.error("Could not extract any content from the provided URL(s). Possible reasons: Website requires JavaScript, blocks scraping, unusual structure, or all links visited were non-HTML.")
            if crawling_errors: st.subheader("Crawling Errors Encountered:"); st.json(crawling_errors)
            st.stop()

        st.success(f"Crawling complete. Extracted content from {len(all_extracted_content)} pages across {len(valid_urls)} starting URL(s). Total unique pages visited: {len(all_visited_urls)}.")

        status_text.text("🤖 Asking AI to analyze content and identify modules...")
        with st.spinner("AI is thinking... This might take a moment."):
            extracted_data, error_message = generate_modules_with_gemini(all_extracted_content)

        progress_bar.progress(1.0)

        if error_message:
            status_text.error(f"AI Processing Error: {error_message}")
            st.warning("Could not generate structured output. Check logs or try again. The AI might have had trouble with the content or format.")
        elif extracted_data:
            status_text.success("✅ Successfully extracted modules!")
            st.subheader("Extracted Modules and Submodules:")
            st.json(extracted_data)
            with st.expander("Show Raw Extracted Text (Preview - First 5000 chars)"):
                 preview_text = "\\n".join(all_extracted_content.values())[:5000]
                 st.text_area("Raw Text Sent to AI (Preview)", preview_text , height=300)
            with st.expander("Show Visited URLs"):
                 st.write(sorted(list(all_visited_urls)))
        else:
            status_text.error("🔴 AI analysis failed to produce results. No specific error message provided, check logs.")


# --- Main execution block for streamlit_app.py ---
if __name__ == '__main__':
    run_streamlit_app()

"""

# STEP 8: Write the Streamlit app code to a file
try:
    with open("streamlit_app.py", "w") as f:
        f.write(app_code)
    logging.info("Streamlit app code written to streamlit_app.py")
except Exception as e:
    st.error(f"Failed to write streamlit_app.py: {e}")
    logging.error(f"Failed to write streamlit_app.py: {e}")
    sys.exit("Cannot proceed without writing app file.")

# STEP 9: Kill any existing Ngrok tunnel and Streamlit processes
ngrok.kill()

# STEP 10: Launch Streamlit using Ngrok

if not HARDCODED_NGROK_AUTH_TOKEN or "YOUR_NGROK_AUTH_TOKEN_HERE" in HARDCODED_NGROK_AUTH_TOKEN:
    st.error("🔴 Ngrok Authtoken is missing or is still the placeholder in the code. Cannot expose the app.")
    logging.error("Ngrok Authtoken missing or placeholder detected. Cannot create tunnel.")
else:
    if not HARDCODED_GOOGLE_API_KEY or "YOUR_GEMINI_API_KEY_HERE" in HARDCODED_GOOGLE_API_KEY:
        st.error("🔴 Cannot launch Streamlit because the Gemini API Key is missing or is still the placeholder.")
        logging.error("Gemini API key missing or placeholder detected. Aborting Streamlit launch.")
    else:
        logging.info("API Key and Ngrok Token seem present. Proceeding with Streamlit launch.")
        try:
            log_level_option = "--logger.level=info"
            public_url = ngrok.connect(8501)
            print(f"🚀 Streamlit App URL: {public_url}")
            st.success(f"🚀 Streamlit App is live at: {public_url}")
            st.markdown(f"Click here to open the app: [{public_url}]({public_url})")
            st.warning("🚨 Remember: This app uses hardcoded keys and is NOT secure for sharing.", icon="⚠️")

            streamlit_command = f"GOOGLE_API_KEY='{HARDCODED_GOOGLE_API_KEY}' nohup streamlit run streamlit_app.py --server.port 8501 --server.enableCORS=false --server.enableXsrfProtection=false {log_level_option} > streamlit_log.txt 2>&1 &"
            print(f"Executing command: GOOGLE_API_KEY=***REDACTED*** nohup streamlit run ...")

            !{streamlit_command}

            st.info("Streamlit process launched in the background. See 'streamlit_log.txt' for runtime logs from the app.")
            st.info("Keep this Colab cell running to maintain the Ngrok tunnel.")
            st.info("To stop the app, interrupt or stop the execution of this Colab cell.")

        except Exception as e:
            st.error(f"Failed to start Ngrok tunnel or Streamlit: {e}")
            logging.error(f"Failed to start Ngrok/Streamlit: {e}")

st.markdown("---")
st.markdown("**Keep this Colab cell running to use the Streamlit app via the Ngrok URL.**")
st.markdown("**Interrupt or stop cell execution to shut down the app and the tunnel.**")















